#!/bin/sh
# To be able to run calabash from any folder, put this script in $PATH
# This assumes that you unpacked to your user home directory.
# If needed, change the path to calabash.jar to reflect the actual path on your system. 
CALABASH_JAR="$(dirname -- "$0")/calabash.jar"
java -Xmx1024m -jar $CALABASH_JAR "$@"
    
